@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

class Graphe {}
class Arete {}
class Fourmis {}

class Reine {}

class Soldat {}

class Noeud{}

class Etranger {}


Graphe --> Noeud
Noeud -> Arete
Graphe -> Arete
Noeud --> Fourmis
Fourmis "Occupé par une" --> Reine
Fourmis --> Etranger
Reine --> Soldat


@enduml