@startuml
'https://plantuml.com/sequence-diagram

skinparam style strictuml
skinparam responseMessageBelowArrow true
hide footbox
'autonumber

participant "Graphe" as graphe
participant "Noeud" as noeud
participant "Reine" as reine
participant "Soldat" as soldat

-> graphe++:Graphe(longueur, largueur)
graphe -> graphe++ : CreationEmplacement()

-> noeud++:Noeud(g)



@enduml