@startuml
'https://plantuml.com/sequence-diagram

skinparam style strictuml
skinparam responseMessageBelowArrow true
hide footbox
'autonumber

participant "Graphe:g" as graphe
participant "Noeud:n" as noeud

' ---------GRAPHE--------------
-> graphe++:Graphe(longueur, largueur)
graphe -> graphe++ : CreationEmplacement()
    return

' ---------NOEUD--------------
-> noeud++:Noeud(g)
graphe <- noeud++ : getEmplacementNoeud(n)
    return noeud

' ---------COLONIE--------------
create Colonie
noeud --> Colonie : <<Create>>

' ---------REINE--------------
participant "Reine:r" as reine
-> reine++ : Reine(n,g)

reine -> reine++ : setResidenceNaissance(n)
    return
reine -> reine++ : setPositionActuel(n)
    return
reine -> reine++ : setColonie(c)
    return
reine -> reine++ : donnerNaissance(nbSoldat, n, c, g)

loop i<nbSoldat
    ' ---------SOLDAT--------------
    create Soldat
    reine --> Soldat : <<Create>>
    Soldat -> Soldat++ : enMouvement()
    loop i<g.getNbrNoeudDansGraphe
        Soldat -> Soldat : patrouille()
        ' ---------ARETES--------------
        create Arettes
        Soldat --> Arettes : <<Create>>
        Arettes -> Arettes++ : rechercheAretes()
            return
        Arettes -> Arettes++ : deplacementNoeud()
        Arettes -> noeud : setCoordonneNoeud(noeud2)
            return
        Soldat -> Soldat : setPositionActuel(noeud2)
    end
end


@enduml